begin;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.procplus_api_keys (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 3 and 80),
  key_prefix text not null,
  key_hash text not null unique,
  scopes text[] not null default array['processes:read']::text[],
  expires_at timestamptz,
  last_used_at timestamptz,
  active boolean not null default true,
  created_by uuid not null default auth.uid() references public.profiles(id),
  created_at timestamptz not null default now(),
  revoked_at timestamptz,
  check (
    scopes <@ array[
      'processes:read',
      'suppliers:read',
      'contracts:read'
    ]::text[]
  )
);

create index if not exists procplus_api_keys_org_idx
on public.procplus_api_keys(organization_id, created_at desc);

create table if not exists public.procplus_api_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  api_key_id uuid references public.procplus_api_keys(id) on delete set null,
  method text not null,
  endpoint text not null,
  status_code integer not null,
  request_id uuid not null default gen_random_uuid(),
  created_at timestamptz not null default now()
);

create index if not exists procplus_api_events_org_idx
on public.procplus_api_events(organization_id, created_at desc);

alter table public.procplus_api_keys enable row level security;
alter table public.procplus_api_events enable row level security;

drop policy if exists procplus_api_keys_read on public.procplus_api_keys;
create policy procplus_api_keys_read
on public.procplus_api_keys for select to authenticated
using (public.has_organization_role(organization_id, array['owner','admin']));

drop policy if exists procplus_api_events_read on public.procplus_api_events;
create policy procplus_api_events_read
on public.procplus_api_events for select to authenticated
using (public.has_organization_role(organization_id, array['owner','admin','compliance','auditor']));

create or replace function public.create_procplus_api_key(
  p_organization_id uuid,
  p_name text,
  p_scopes text[] default array['processes:read']::text[],
  p_expires_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_token text;
  v_key public.procplus_api_keys;
  v_allowed text[] := array[
    'processes:read',
    'suppliers:read',
    'contracts:read'
  ]::text[];
begin
  if not public.has_organization_role(p_organization_id, array['owner','admin']) then
    raise exception 'Apenas proprietários e administradores podem criar credenciais API.';
  end if;
  if char_length(trim(coalesce(p_name, ''))) < 3 then
    raise exception 'Indique um nome com pelo menos 3 caracteres.';
  end if;
  if coalesce(array_length(p_scopes, 1), 0) = 0 or not (p_scopes <@ v_allowed) then
    raise exception 'Seleccione pelo menos um âmbito de acesso válido.';
  end if;
  if p_expires_at is not null and p_expires_at <= now() then
    raise exception 'A validade deve terminar numa data futura.';
  end if;

  v_token := 'pp_live_' || encode(gen_random_bytes(24), 'hex');
  insert into public.procplus_api_keys (
    organization_id, name, key_prefix, key_hash, scopes, expires_at
  ) values (
    p_organization_id,
    trim(p_name),
    left(v_token, 16),
    encode(digest(v_token, 'sha256'), 'hex'),
    p_scopes,
    p_expires_at
  )
  returning * into v_key;

  return jsonb_build_object(
    'id', v_key.id,
    'name', v_key.name,
    'token', v_token,
    'key_prefix', v_key.key_prefix,
    'scopes', v_key.scopes,
    'expires_at', v_key.expires_at,
    'created_at', v_key.created_at
  );
end;
$$;

create or replace function public.revoke_procplus_api_key(p_key_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_key public.procplus_api_keys;
begin
  select * into v_key from public.procplus_api_keys where id = p_key_id;
  if v_key.id is null then
    raise exception 'Credencial API não encontrada.';
  end if;
  if not public.has_organization_role(v_key.organization_id, array['owner','admin']) then
    raise exception 'Apenas proprietários e administradores podem revogar credenciais API.';
  end if;

  update public.procplus_api_keys
  set active = false, revoked_at = now()
  where id = p_key_id and active;

end;
$$;

revoke all on function public.create_procplus_api_key(uuid,text,text[],timestamptz) from public;
revoke all on function public.revoke_procplus_api_key(uuid) from public;
grant execute on function public.create_procplus_api_key(uuid,text,text[],timestamptz) to authenticated;
grant execute on function public.revoke_procplus_api_key(uuid) to authenticated;
grant select on public.procplus_api_keys, public.procplus_api_events to authenticated;

commit;
